name: Run a bash command

on: # Could even schedule this process 
  workflow_dispatch: # If manually run in Github interface
  push: # If push happens to the repository 
    branches: [main] # Follows same steps as for paths, given changes to main branch 
    paths:
      - 'Dockerfile' # If this is changed 
      - .github/workflows/publish_docker_image.yml # File name and location
      - 'conda-linux-64.lock'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # FILL THESE ON GITHUB SETTINGS, SECRETS
          password: ${{ secrets.DOCKER_PASSWORD }} # FILL THESE ON GITHUB SETTINGS, SECRETS

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: kayleeli/dsci310_g6_milestone1 # CHANGE THIS IMAGE 
          tags: |
            type=raw, value={{sha}},enable=${{github.ref_type != 'tag' }}
            type=raw, value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}